/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EdgeKind = { 'childOf' : null } |
  { 'spouseOriginOf' : null };
export interface EdgeRecord {
  'kind' : EdgeKind,
  'toFamilyId' : string,
  'viaPersonName' : string,
  'fromFamilyId' : string,
}
export interface FamilyRecord {
  'createdAt' : bigint,
  'parentFamilyId' : [] | [string],
  'familyId' : string,
  'rootName' : string,
  'canisterId' : Principal,
}
export interface _SERVICE {
  /**
   * / Add a relationship edge between two existing families.
   */
  'linkFamilies' : ActorMethod<
    [string, string, EdgeKind, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Return all relationship edges.
   */
  'listEdges' : ActorMethod<[], Array<EdgeRecord>>,
  /**
   * / Return all registered family records.
   */
  'listFamilies' : ActorMethod<[], Array<FamilyRecord>>,
  /**
   * / Call the child canister's whoAmI() and return its response.
   */
  'pingChild' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  /**
   * / Create a new child Family canister, fund it, register it, and optionally
   * / add a #childOf edge to the parent family.
   */
  'plantTree' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : [string, Principal] } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];