/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EdgeKind = IDL.Variant({
  'childOf' : IDL.Null,
  'spouseOriginOf' : IDL.Null,
});
export const EdgeRecord = IDL.Record({
  'kind' : EdgeKind,
  'toFamilyId' : IDL.Text,
  'viaPersonName' : IDL.Text,
  'fromFamilyId' : IDL.Text,
});
export const FamilyRecord = IDL.Record({
  'createdAt' : IDL.Int,
  'parentFamilyId' : IDL.Opt(IDL.Text),
  'familyId' : IDL.Text,
  'rootName' : IDL.Text,
  'canisterId' : IDL.Principal,
});

export const idlService = IDL.Service({
  'linkFamilies' : IDL.Func(
      [IDL.Text, IDL.Text, EdgeKind, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'listEdges' : IDL.Func([], [IDL.Vec(EdgeRecord)], ['query']),
  'listFamilies' : IDL.Func([], [IDL.Vec(FamilyRecord)], ['query']),
  'pingChild' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'plantTree' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [
        IDL.Variant({
          'ok' : IDL.Tuple(IDL.Text, IDL.Principal),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EdgeKind = IDL.Variant({
    'childOf' : IDL.Null,
    'spouseOriginOf' : IDL.Null,
  });
  const EdgeRecord = IDL.Record({
    'kind' : EdgeKind,
    'toFamilyId' : IDL.Text,
    'viaPersonName' : IDL.Text,
    'fromFamilyId' : IDL.Text,
  });
  const FamilyRecord = IDL.Record({
    'createdAt' : IDL.Int,
    'parentFamilyId' : IDL.Opt(IDL.Text),
    'familyId' : IDL.Text,
    'rootName' : IDL.Text,
    'canisterId' : IDL.Principal,
  });
  
  return IDL.Service({
    'linkFamilies' : IDL.Func(
        [IDL.Text, IDL.Text, EdgeKind, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'listEdges' : IDL.Func([], [IDL.Vec(EdgeRecord)], ['query']),
    'listFamilies' : IDL.Func([], [IDL.Vec(FamilyRecord)], ['query']),
    'pingChild' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'plantTree' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [
          IDL.Variant({
            'ok' : IDL.Tuple(IDL.Text, IDL.Principal),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };